int checks = 0;
void Check(bool value, string name)
{
    if (!value) throw new System.InvalidOperationException(name);
    checks++;
}
var bag = new SSW.CastStock();
bag.Reset(1);
Check(!bag.Swap(0, 1, 0), "empty inventory cannot swap");
bag.Add(1, 0, 1);
var first = bag.Held;
bag.Add(2, 0, 1);
var second = bag.Next;
Check(bag.Swap(first.Id, 1, 0.1), "store held potion");
Check(bag.Pocket.Id == first.Id && bag.Held.Id == second.Id && bag.Next.Id == 0, "store promotes reserve");
Check(!bag.Swap(second.Id, 1, 0.2) && !bag.Take(first.Id, 1, 0.2, out _), "cannot reswap or throw pocket item");
Check(bag.Take(second.Id, 1, 0.3, out _) && !bag.PocketUsed, "successful throw unlocks pocket");
Check(bag.Swap(0, 1, 0.4) && bag.Held.Id == first.Id && bag.Pocket.Id == 0, "retrieve with empty hand");
Check(bag.Take(first.Id, 1, 0.5, out _) && !bag.Take(first.Id, 1, 0.6, out _), "retrieved item can only be spent once");
bag.Add(3, 1, 1);
bag.Add(4, 1, 1);
bag.Swap(bag.Held.Id, 1, 1.1);
bag.Take(bag.Held.Id, 1, 1.2, out _);
bag.Add(5, 1.3, 1);
bag.Add(6, 1.4, 1);
var saved = bag.Pocket;
var held = bag.Held;
var next = bag.Next;
Check(bag.Swap(held.Id, 1, 1.5), "exchange occupied hand and pocket");
Check(bag.Held.Id == saved.Id && bag.Pocket.Id == held.Id && bag.Next.Id == next.Id, "exchange preserves next potion and identity");
Check(!bag.Swap(0, 1, 1.6) && !bag.Swap(99999, 1, 1.6), "invalid requests do not mutate inventory");
bag.Take(bag.Held.Id, 1, 1.7, out _);
held = bag.Held;
bag.Add(7, 1.8, 1);
bag.Add(8, 1.9, 1);
saved = bag.Pocket;
next = bag.Next;
var live = bag.Held;
Check(bag.Swap(held.Id, 1, 2), "delayed swap accepts issued retired item within grace");
Check(bag.Pocket.Id == held.Id && bag.Held.Id == live.Id && bag.Next.Id == next.Id, "delayed swap leaves newer live slots intact");
Check(bag.Take(saved.Id, 1, 2.1, out _), "previous pocket follows delayed brewing timeline");
Check(!bag.Take(saved.Id, 1, 2.2, out _) && !bag.Take(held.Id, 1, 2.2, out _), "delayed swap cannot duplicate either potion");
saved = bag.Pocket;
bag.Reset(2);
Check(bag.Pocket.Kind == saved.Kind && bag.Pocket.Id != saved.Id, "epoch renews stored identity without losing potion");
Check(!bag.Swap(bag.Held.Id, 1, 2.3) && !bag.Swap(saved.Id, 2, 2.3), "old epoch and old item rejected");
var late = new SSW.CastStock();
late.Reset(1);
late.Add(1, 0, 1);
first = late.Held;
late.Add(2, 0, 1);
late.Add(3, 0, 1);
Check(!late.Swap(first.Id, 1, 1), "expired delayed swap rejected");
return new { passed = checks };
