int count = 0;
System.Action<bool, string> check = (ok, name) =>
{
    if (!ok) throw new System.Exception(name);
    count++;
};
var stock = new SSW.CastStock();
stock.Reset(4);
check(stock.Held.Kind == -1 && stock.Next.Kind == -1, "empty");
stock.Add(2, 0, 0.6);
var first = stock.Held;
stock.Add(2, 1.5, 0.6);
var second = stock.Next;
check(first.Id != second.Id && first.Kind == second.Kind, "same kind has distinct ids");
check(!stock.Take(second.Id, 4, 1.6, out _), "reserve cannot skip held");
stock.Add(1, 3, 0.6);
var third = stock.Next;
check(stock.Take(first.Id, 4, 3.5, out int kind) && kind == 2, "delayed replaced stock keeps kind");
check(stock.Held.Id == second.Id && stock.Next.Id == third.Id, "old stock leaves current slots intact");
check(!stock.Take(first.Id, 4, 3.51, out _), "old stock cannot replay");
check(stock.Take(second.Id, 4, 3.66, out kind) && kind == 2, "fast second shot after delayed first");
check(stock.Held.Id == third.Id && stock.Next.Id == 0, "second shot promotes one reserve");
check(!stock.Take(9999, 4, 3.7, out _) && !stock.Take(0, 4, 3.7, out _), "unissued ids rejected");
stock.Add(0, 4, 100);
stock.Add(3, 5, 100);
check(!stock.Take(third.Id, 4, 6.25, out _), "grace capped and expiry exclusive");
var beforeReset = stock.Held;
stock.Reset(5);
check(stock.Held.Kind == beforeReset.Kind && stock.Held.Id != beforeReset.Id, "epoch preserves kind renews id");
check(!stock.Take(beforeReset.Id, 5, 6.3, out _), "old epoch id rejected with new epoch");
check(!stock.Take(stock.Held.Id, 4, 6.3, out _), "old epoch rejected with current id");
check(stock.Take(stock.Held.Id, 5, 6.3, out _), "new epoch current stock accepted");
check(stock.Take(stock.Held.Id, 5, 6.46, out _), "quick second stock accepted");
check(stock.Held.Id == 0 && stock.Next.Id == 0, "both spent empty");
stock.Reset(6);
stock.Add(2, 10, 1.25);
var delayed = stock.Held;
stock.Add(1, 11.5, 1.25);
stock.Add(3, 13, 1.25);
check(stock.Take(delayed.Id, 6, 14.1, out kind) && kind == 2, "RTT spike preserves replaced stock for 1.1 seconds");
check(!stock.Take(delayed.Id, 6, 14.11, out _), "delayed stock still cannot replay");
return count + " stock checks passed";
